#############################################################################
# Makefile for building: ClothSim
# Generated by qmake (3.0) (Qt 5.5.1)
# Project:  ClothSim.pro
# Template: app
# Command: /home/infinte/Qt5.5.1/5.5/gcc_64/bin/qmake -o Makefile ClothSim.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT5BUILD -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -std=c++0x -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -Iinclude -I/home/infinte/Qt5.5.1/5.5/gcc_64/include -I/home/infinte/Qt5.5.1/5.5/gcc_64/include/QtGui -I/home/infinte/Qt5.5.1/5.5/gcc_64/include/QtCore -I. -I/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/linux-g++
QMAKE         = /home/infinte/Qt5.5.1/5.5/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = ClothSim1.0.0
DISTDIR = /home/infinte/Documents/ClothSim/ClothSim/ClothSim/.tmp/ClothSim1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/infinte/Qt5.5.1/5.5/gcc_64 -Wl,-rpath,/home/infinte/Qt5.5.1/5.5/gcc_64/lib
LIBS          = $(SUBLIBS) -lglut -lGLU -lGL -L/home/infinte/Qt5.5.1/5.5/gcc_64/lib -lQt5Gui -L/usr/lib64 -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/particle.cpp \
		src/spring.cpp \
		src/cloth.cpp \
		src/vec3.cpp \
		src/inextensible.cpp \
		src/mat3x3.cpp \
		src/mat2x3.cpp 
OBJECTS       = particle.o \
		spring.o \
		cloth.o \
		vec3.o \
		inextensible.o \
		mat3x3.o \
		mat2x3.o
DIST          = fragshader.frag \
		vertexshader.vert \
		ClothSim.pro include/cloth.h \
		include/particle.h \
		include/spring.h \
		include/vec3.h \
		include/constants.h \
		include/inextensible.h \
		include/mat3x3.h \
		include/mat2x3.h src/particle.cpp \
		src/spring.cpp \
		src/cloth.cpp \
		src/vec3.cpp \
		src/inextensible.cpp \
		src/mat3x3.cpp \
		src/mat2x3.cpp
QMAKE_TARGET  = ClothSim
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = ClothSim


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ClothSim.pro .qmake.cache /home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/linux-g++/qmake.conf /home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/spec_pre.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/unix.conf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/linux.conf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/sanitize.conf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/gcc-base.conf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/g++-base.conf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/g++-unix.conf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/qconfig.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt_functions.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt_config.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/linux-g++/qmake.conf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.cache \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/exclusive_builds.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/default_pre.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/resolve_config.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/default_post.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/unix/opengl.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/resources.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/moc.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/unix/thread.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/c++11.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/warn_on.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/testcase_targets.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/exceptions.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/yacc.prf \
		/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/lex.prf \
		ClothSim.pro \
		/home/infinte/Qt5.5.1/5.5/gcc_64/lib/libQt5Gui.prl \
		/home/infinte/Qt5.5.1/5.5/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ClothSim.pro
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/spec_pre.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/unix.conf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/linux.conf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/sanitize.conf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/gcc-base.conf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/gcc-base-unix.conf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/g++-base.conf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/common/g++-unix.conf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/qconfig.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcollision_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3dquickrenderer_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_3drenderer_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_location.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_script.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt_functions.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt_config.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/linux-g++/qmake.conf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/spec_post.prf:
.qmake.cache:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/exclusive_builds.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/default_pre.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/resolve_config.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/default_post.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/unix/opengl.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/qt.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/resources.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/moc.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/unix/thread.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/c++11.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/warn_on.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/testcase_targets.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/exceptions.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/yacc.prf:
/home/infinte/Qt5.5.1/5.5/gcc_64/mkspecs/features/lex.prf:
ClothSim.pro:
/home/infinte/Qt5.5.1/5.5/gcc_64/lib/libQt5Gui.prl:
/home/infinte/Qt5.5.1/5.5/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ClothSim.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents include/cloth.h include/particle.h include/spring.h include/vec3.h include/constants.h include/inextensible.h include/mat3x3.h include/mat2x3.h $(DISTDIR)/
	$(COPY_FILE) --parents src/particle.cpp src/spring.cpp src/cloth.cpp src/vec3.cpp src/inextensible.cpp src/mat3x3.cpp src/mat2x3.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

particle.o: src/particle.cpp include/particle.h \
		include/vec3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o particle.o src/particle.cpp

spring.o: src/spring.cpp include/spring.h \
		include/vec3.h \
		include/particle.h \
		include/constants.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o spring.o src/spring.cpp

cloth.o: src/cloth.cpp include/cloth.h \
		include/particle.h \
		include/vec3.h \
		include/spring.h \
		include/constants.h \
		include/inextensible.h \
		include/mat3x3.h \
		include/mat2x3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cloth.o src/cloth.cpp

vec3.o: src/vec3.cpp include/vec3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vec3.o src/vec3.cpp

inextensible.o: src/inextensible.cpp include/inextensible.h \
		include/vec3.h \
		include/particle.h \
		include/spring.h \
		include/constants.h \
		include/mat3x3.h \
		include/mat2x3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inextensible.o src/inextensible.cpp

mat3x3.o: src/mat3x3.cpp include/mat3x3.h \
		include/vec3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mat3x3.o src/mat3x3.cpp

mat2x3.o: src/mat2x3.cpp include/mat2x3.h \
		include/vec3.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mat2x3.o src/mat2x3.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

